name: haptic-cache
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pillow
  - pyyaml
  - pandas
  - matplotlib
  - opencv
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
